### ISSUE TITLE
Docker image not valid for linux/arm64/v8

### ISSUE THREAD

**Issue by jorburmar** [hugo-vrijswijk/tgtg#65]
Docker image not valid for linux/arm64/v8
Would it be possible to make it compatible?
Thx!

**Comment by hugo-vrijswijk** [comment]
@jorburmar  this is fixed in 0.6.2

**Comment by jorburmar** [comment]
and how is it used?
I have tried:
ghcr.io/hugo-vrijswijk/tgtg:arm64
ghcr.io/hugo-vrijswijk/tgtg:arm
unsuccessfully
thx!

**Comment by hugo-vrijswijk** [comment]
There's no separate tag for arm, instead docker multi-arch is used. If you just pull `ghc. r.io/hugo-vrijswijk/tgtg` it should pull the right one for your platform

**Comment by jorburmar** [comment]
Now it works, thank you very much!

**Comment by hugo-vrijswijk** [comment]
Good to hear! Thanks for opening the issue too, I didn't realize arm images were broken
